/**
 * Facecards — Google Apps Script web app.
 *
 * Data lives in the spreadsheet named by CONFIG.SPREADSHEET_ID:
 *   - first tab  : one row per student/section enrollment (headers include
 *                  studentNumber, firstName, lastName, nickname, period, course,
 *                  gender, teacherEmail, grade, teacherName, ...)
 *   - `photos` tab : studentNumber -> Drive fileId, generated by refreshPhotoMap()
 *   - `admins` tab : one admin email per row (header `email`)
 *
 * Photos are surfaced as drive.google.com/thumbnail URLs from the folder named
 * by CONFIG.DRIVE_FOLDER_ID (shared view-only with the domain).
 *
 * Access: deployed with webapp.access DOMAIN + executeAs USER_DEPLOYING, so the
 * app reads the deployer's private spreadsheet while only domain users can open
 * it. doGet further restricts to exact @berkeley.net addresses (excluding
 * students at @students.berkeley.net) and scopes each viewer to their own
 * sections. Admins (from the `admins` tab) may impersonate any user via ?as=.
 */

var PHOTOS_SHEET = 'photos';
var ADMINS_SHEET = 'admins';

function doGet(e) {
  e = e || {};
  var params = e.parameter || {};

  var actual = normalizeEmail(Session.getActiveUser().getEmail());

  if (!isBerkeleyStaff(actual)) {
    return HtmlService.createHtmlOutput(
      '<p style="font-family:system-ui,sans-serif;margin:2rem">Not authorized.</p>'
    ).setTitle('Facecards');
  }

  var isAdmin = readAdmins().has(actual);
  var asParam = isAdmin && params.as ? qualifyEmail(params.as) : '';
  var effective = asParam || actual;
  var impersonating = effective !== actual;

  var model = buildModel(effective);

  var ctx = {
    actual: actual,
    effective: effective,
    impersonating: impersonating,
    isAdmin: isAdmin,
    baseUrl: getBaseUrl(),
  };

  // No sections for this viewer -> landing page.
  if (Object.keys(model.classes).length === 0) {
    var landing = HtmlService.createTemplateFromFile('landing');
    landing.ctx = ctx;
    return page(landing);
  }

  var route = {
    mode: params.mode || 'home', // home | learn | review
    scope: params.scope || '', // '' | class | all
    id: params.id || '', // class slug
  };

  var t = HtmlService.createTemplateFromFile('index');
  t.modelJson = jsonForScript(model);
  t.routeJson = jsonForScript(route);
  t.ctxJson = jsonForScript(ctx);
  return page(t);
}

/** Included by index.html / landing.html to inline the client partials. */
function include(name) {
  return HtmlService.createHtmlOutputFromFile(name).getContent();
}

/**
 * Build the data model scoped to one viewer email: only the sections whose
 * teacherEmail matches. Returns { teacherLast, classes } where classes is keyed
 * by slug and each student is joined to its photo fileId.
 */
function buildModel(email) {
  var rows = readStudents().filter(function (r) {
    return normalizeEmail(r.teacherEmail) === email;
  });
  var photos = readPhotoMap();

  var classes = {};
  var teacherLast = '';

  // A "class" is the group of students a teacher sees together — one room at one
  // period. Several course codes can share that slot (e.g. Biology + Biology H),
  // so we key on room + period and collect the distinct course names for the
  // display name.
  rows.forEach(function (s) {
    var lastName = String(s.teacherName || '').replace(/,.*$/, '');
    var teacher = String(s.teacherEmail || '').replace(/@.*$/, '').toLowerCase();
    var slug = slugify(s.room + '-p-' + s.period + '-' + teacher);
    teacherLast = lastName;

    if (!(slug in classes)) {
      classes[slug] = {
        slug: slug,
        room: s.room,
        period: s.period,
        teacherLast: lastName,
        courses: [], // distinct course names sharing this room + period
        students: [],
      };
    }
    var c = classes[slug];
    var course = String(s.course || '');
    if (course && c.courses.indexOf(course) === -1) c.courses.push(course);
    c.students.push({
      studentNumber: String(s.studentNumber),
      firstName: s.firstName,
      lastName: s.lastName,
      nickname: s.nickname,
      grade: s.grade,
      gender: s.gender,
      course: s.course,
      period: s.period,
      fileId: photos[String(s.studentNumber)] || '',
    });
  });

  // Name each class from its course list: "Biology / Biology H Period 2".
  Object.keys(classes).forEach(function (slug) {
    var c = classes[slug];
    c.courses.sort(function (a, b) {
      return a.localeCompare(b);
    });
    c.name = c.courses.join(' / ') + ' Period ' + c.period;
  });

  return { teacherLast: teacherLast, classes: classes };
}

/**
 * (Re)build the `photos` tab by scanning CONFIG.DRIVE_FOLDER_ID for
 * <studentNumber>.jpg files. Run manually from the Apps Script editor after
 * uploading new photos.
 */
function refreshPhotoMap() {
  var folder = DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID);
  var files = folder.getFiles();
  var rows = [];
  while (files.hasNext()) {
    var f = files.next();
    var m = f.getName().match(/^(\d+)\.jpe?g$/i);
    if (m) rows.push([m[1], f.getId()]);
  }
  rows.sort(function (a, b) {
    return Number(a[0]) - Number(b[0]);
  });

  var ss = spreadsheet();
  var sheet = ss.getSheetByName(PHOTOS_SHEET) || ss.insertSheet(PHOTOS_SHEET, ss.getNumSheets());
  sheet.clearContents();
  sheet.getRange(1, 1, 1, 2).setValues([['studentNumber', 'fileId']]);
  if (rows.length) sheet.getRange(2, 1, rows.length, 2).setValues(rows);
  Logger.log('Wrote ' + rows.length + ' photo rows to the "' + PHOTOS_SHEET + '" tab.');
}

/* ------------------------------------------------------------------ */
/* Spreadsheet helpers                                                 */
/* ------------------------------------------------------------------ */

function spreadsheet() {
  return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);
}

/** Student rows come from the first tab of the spreadsheet. */
function readStudents() {
  return sheetToObjects(spreadsheet().getSheets()[0]);
}

/** studentNumber -> fileId from the `photos` tab. */
function readPhotoMap() {
  var sheet = spreadsheet().getSheetByName(PHOTOS_SHEET);
  var map = {};
  if (!sheet) return map;
  sheetToObjects(sheet).forEach(function (r) {
    if (r.studentNumber !== '' && r.studentNumber != null) {
      map[String(r.studentNumber)] = String(r.fileId);
    }
  });
  return map;
}

/**
 * Lowercased Set of admin emails from the `admins` tab. Reads every cell and
 * keeps anything that resolves to an email — bare usernames get @berkeley.net
 * appended — so the tab can be a plain list of names or full addresses, with or
 * without a header row. (A stray label like "email" becomes
 * "email@berkeley.net", which matches nobody's login and is harmless.)
 */
function readAdmins() {
  var sheet = spreadsheet().getSheetByName(ADMINS_SHEET);
  var out = new Set();
  if (!sheet) return out;
  sheet.getDataRange().getValues().forEach(function (row) {
    row.forEach(function (cell) {
      var email = qualifyEmail(cell);
      if (isEmailShaped(email)) out.add(email);
    });
  });
  return out;
}

/** Read a sheet into an array of objects keyed by the header row. */
function sheetToObjects(sheet) {
  var values = sheet.getDataRange().getValues();
  if (values.length < 2) return [];
  var headers = values[0].map(function (h) {
    return String(h).trim();
  });
  return values
    .slice(1)
    .filter(function (row) {
      return row.some(function (c) {
        return c !== '' && c !== null;
      });
    })
    .map(function (row) {
      var o = {};
      headers.forEach(function (h, i) {
        o[h] = row[i];
      });
      return o;
    });
}

/* ------------------------------------------------------------------ */
/* Small utilities                                                     */
/* ------------------------------------------------------------------ */

function slugify(s) {
  return String(s)
    .replace(/\s+/g, '-')
    .replace(/[^-\w]/g, '')
    .toLowerCase();
}

function normalizeEmail(s) {
  return String(s || '').trim().toLowerCase();
}

// Normalize an email or bare username: trim + lowercase, and append
// @berkeley.net when no domain is given, so "peterseibel" becomes
// "peterseibel@berkeley.net". Used for both the admins tab and ?as=.
function qualifyEmail(s) {
  var v = normalizeEmail(s);
  if (!v) return '';
  if (v.indexOf('@') === -1) v = v + '@berkeley.net';
  return v;
}

function isEmailShaped(s) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}

function isBerkeleyStaff(email) {
  return /@berkeley\.net$/.test(email);
}

function jsonForScript(obj) {
  // Safe to inline inside a <script> via <?!= ?>: escape "<" so a value can
  // never terminate the script element.
  return JSON.stringify(obj).replace(/</g, '\\u003c');
}

function page(template) {
  return template
    .evaluate()
    .setTitle('Facecards')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function getBaseUrl() {
  try {
    return ScriptApp.getService().getUrl() || '';
  } catch (err) {
    return '';
  }
}
