/**
 * Facecards — Google Apps Script web app.
 *
 * Data lives in the spreadsheet named by CONFIG.SPREADSHEET_ID:
 *   - `rosters` tab : one row per student/section enrollment (headers include
 *                  studentNumber, firstName, lastName, nickname, period, course,
 *                  gender, teacherEmail, grade, teacherName, ...)
 *   - `photos` tab : studentNumber -> Drive fileId, generated by refreshPhotoMap()
 *   - `missing photos` tab : personId, studentNumber of students with no photo,
 *                  also generated by refreshPhotoMap()
 *   - `admins` tab : one admin email per row (header `email`)
 *   - `staff` tab : the BHS staff directory, generated by refreshStaffDirectory()
 *   - `staff overrides` tab : staff members' corrections to their own entries
 *                  (name/role fields, a self-taken photo as a small JPEG data
 *                  URL, and an opt-out flag), written from the ?staff-edit form
 *
 * Photos are surfaced as drive.google.com/thumbnail URLs from the folder named
 * by CONFIG.DRIVE_FOLDER_ID (shared view-only with the domain).
 *
 * Access: deployed with webapp.access DOMAIN + executeAs USER_DEPLOYING, so the
 * app reads the deployer's private spreadsheet while only domain users can open
 * it. doGet further restricts to exact @berkeley.net addresses (excluding
 * students at @students.berkeley.net) and scopes each viewer to their own
 * sections. Admins (from the `admins` tab) may impersonate any user via ?as=.
 */

var ROSTERS_SHEET = 'rosters';
var PHOTOS_SHEET = 'photos';
var ADMINS_SHEET = 'admins';
var MISSING_PHOTOS_SHEET = 'missing photos';
var LISTS_SHEET = 'lists';
var STAFF_SHEET = 'staff';
var STAFF_OVERRIDES_SHEET = 'staff overrides';

var STAFF_DIRECTORY_URL = 'https://bhs.berkeleyschools.net/staff/';

function doGet(e) {
  e = e || {};
  var params = e.parameter || {};
  var t0 = new Date().getTime();
  console.log('doGet params: ' + JSON.stringify(params));

  var tStep = new Date().getTime();
  var viewer = resolveViewer(params.as);
  logTime('  resolveViewer', tStep);

  if (!viewer) {
    return HtmlService.createHtmlOutput(
      '<p style="font-family:system-ui,sans-serif;margin:2rem">Not authorized.</p>'
    ).setTitle('Facecards');
  }
  var effective = viewer.effective;

  tStep = new Date().getTime();
  var baseUrl = getBaseUrl();
  logTime('  getBaseUrl', tStep);
  var ctx = {
    actual: viewer.actual,
    effective: viewer.effective,
    impersonating: viewer.impersonating,
    isAdmin: viewer.isAdmin,
    baseUrl: baseUrl,
  };

  // Shared-with view: a table of students the viewer shares with another teacher.
  if (params['shared-with']) {
    var st = HtmlService.createTemplateFromFile('index');
    st.modelJson = jsonForScript({ teacherLast: '', classes: {} });
    st.routeJson = jsonForScript({ mode: 'shared', scope: '', id: '' });
    st.sharedJson = jsonForScript(buildSharedModel(effective, String(params['shared-with'])));
    st.staffJson = jsonForScript(null);
    st.staffEntryJson = jsonForScript(null);
    st.ctxJson = jsonForScript(ctx);
    logTime('doGet shared-with build', t0);
    return page(st);
  }

  // Shared overview: every teacher the viewer shares students with, each with a
  // face grid linking to that teacher's shared-with page.
  if (params.shared !== undefined) {
    var ot = HtmlService.createTemplateFromFile('index');
    ot.modelJson = jsonForScript({ teacherLast: '', classes: {} });
    ot.routeJson = jsonForScript({ mode: 'shared-overview', scope: '', id: '' });
    ot.sharedJson = jsonForScript(buildSharedOverview(effective));
    ot.staffJson = jsonForScript(null);
    ot.staffEntryJson = jsonForScript(null);
    ot.ctxJson = jsonForScript(ctx);
    logTime('doGet shared-overview build', t0);
    return page(ot);
  }

  // Staff directory: the scraped BHS staff list. The same for every viewer,
  // and handled before the landing check so it works even for viewers with no
  // sections of their own.
  if (params.staff !== undefined) {
    var sf = HtmlService.createTemplateFromFile('index');
    sf.modelJson = jsonForScript({ teacherLast: '', classes: {} });
    sf.routeJson = jsonForScript({ mode: 'staff', scope: '', id: '' });
    sf.sharedJson = jsonForScript(null);
    sf.staffJson = jsonForScript(publicStaffModel());
    sf.staffEntryJson = jsonForScript(null);
    sf.ctxJson = jsonForScript(ctx);
    logTime('doGet staff build', t0);
    return page(sf);
  }

  // Staff self-edit: a form for correcting one's own directory entry, saved to
  // the `staff overrides` tab so refreshStaffDirectory can't clobber it. The
  // viewer's own entry is resolved server-side from the full (unfiltered)
  // model, so someone who has opted out of the Staff section still gets
  // their entry here and can opt back in.
  if (params['staff-edit'] !== undefined) {
    var se = HtmlService.createTemplateFromFile('index');
    se.modelJson = jsonForScript({ teacherLast: '', classes: {} });
    se.routeJson = jsonForScript({ mode: 'staff-edit', scope: '', id: '' });
    se.sharedJson = jsonForScript(null);
    se.staffJson = jsonForScript(null);
    se.staffEntryJson = jsonForScript(staffEntryFor(effective));
    se.ctxJson = jsonForScript(ctx);
    logTime('doGet staff-edit build', t0);
    return page(se);
  }

  var model = buildModel(effective);

  // Nothing to show this viewer (no sections and no custom lists) -> landing
  // page. (The lists guard: a model cached before lists existed lacks the key.
  // A staff-scope study deep link doesn't need any sections, so it skips this.)
  if (
    Object.keys(model.classes).length === 0 &&
    Object.keys(model.lists || {}).length === 0 &&
    params.scope !== 'staff'
  ) {
    var landing = HtmlService.createTemplateFromFile('landing');
    landing.ctx = ctx;
    logTime('doGet landing build', t0);
    return page(landing);
  }

  var mode;
  if (
    params.mode === 'learn' ||
    params.mode === 'review' ||
    params.mode === 'browse'
  ) {
    mode = params.mode; // study/browse deep link
  } else if (params.learn !== undefined) {
    mode = 'grid'; // ?learn -> the class face grids
  } else {
    mode = 'menu'; // default -> two-box menu
  }
  var route = {
    mode: mode,
    scope: params.scope || '', // '' | class | all
    id: params.id || '', // class slug
  };

  var t = HtmlService.createTemplateFromFile('index');
  t.modelJson = jsonForScript(model);
  t.routeJson = jsonForScript(route);
  t.sharedJson = jsonForScript(null);
  // Staff study deep links (?mode=learn&scope=staff) need the staff list too.
  t.staffJson = jsonForScript(route.scope === 'staff' ? publicStaffModel() : null);
  t.staffEntryJson = jsonForScript(null);
  t.ctxJson = jsonForScript(ctx);
  logTime('doGet build (' + mode + ')', t0);
  return page(t);
}

/** Included by index.html / landing.html to inline the client partials. */
function include(name) {
  return HtmlService.createHtmlOutputFromFile(name).getContent();
}

/**
 * Build the data model scoped to one viewer email: only the sections whose
 * teacherEmail matches. Returns { teacherLast, classes } where classes is keyed
 * by slug and each student is joined to its photo fileId.
 */
function buildModel(email) {
  return cachedBig('model:' + username(email), function () {
    return buildModelUncached(email);
  });
}

function buildModelUncached(email) {
  var data = getData();
  var teacher = data.teachers[username(email)];

  var classes = {};
  if (teacher) {
    Object.keys(teacher.periods).forEach(function (period) {
      var sec = teacher.periods[period];
      var slug = slugify(username(email) + '-p' + period);
      var name = sectionName(sec, period);
      classes[slug] = {
        slug: slug,
        name: name,
        period: period,
        teacherLast: teacher.last,
        students: sec.students.map(function (num) {
          var o = studentBase(data, num);
          o.course = sec.courses.join(' / '); // just the course; the card adds "Period N"
          o.period = period;
          o.schedule = scheduleFor(data, num); // full schedule, for browse mode
          return o;
        }),
      };
    });
  }
  return {
    teacherLast: teacher ? teacher.last : '',
    classes: classes,
    lists: listsFor(data, email),
  };
}

/**
 * The viewer's custom lists from the `lists` tab, keyed by slug (the 'list-'
 * prefix keeps them clear of the class slugs, which start with a username). A
 * list may include any student in the roster, so the feature is gated to
 * admins: for a non-admin email this returns null (no lists key on the wire —
 * the client hides the whole section), which also means an admin impersonating
 * a regular teacher sees exactly what that teacher sees. Numbers no longer in
 * the roster are dropped (nothing to show for them).
 */
function listsFor(data, email) {
  var target = qualifyEmail(email);
  if (!readAdmins().has(target)) return null; // custom lists are admin-only
  var lists = {};
  readLists().forEach(function (r) {
    var name = String(r.listName || '').trim();
    var num = String(r.studentNumber || '').trim();
    if (qualifyEmail(r.teacherEmail) !== target || !name || !data.students[num]) return;
    var slug = 'list-' + slugify(name);
    if (!lists[slug]) lists[slug] = { slug: slug, name: name, students: [] };
    var o = studentBase(data, num);
    o.schedule = scheduleFor(data, num); // full schedule, for browse mode
    o.extra = parseExtra(r.extra); // spare TSV columns, shown on the card back
    lists[slug].students.push(o);
  });
  return lists;
}

function buildSharedModel(currentEmail, param) {
  return cachedBig(
    'sharedwith:' + username(currentEmail) + ':' + normalizeEmail(param),
    function () {
      return buildSharedModelUncached(currentEmail, param);
    },
  );
}

function buildSharedModelUncached(currentEmail, param) {
  var data = getData();
  var me = data.teachers[username(currentEmail)];

  var others = resolveTeachers(data, param).filter(function (k) {
    return k !== username(currentEmail);
  });
  if (!me || !others.length) {
    return { resolved: false, param: param };
  }

  var students = [];
  Object.keys(myStudentNums(me)).forEach(function (num) {
    var st = data.students[num];
    if (!st) return;
    var matched = others.filter(function (k) {
      return st.teachers.indexOf(k) !== -1;
    });
    if (!matched.length) return;

    var mine = teacherClassesFor(me, num);
    var otherNames = [];
    var otherPeriods = [];
    matched.forEach(function (k) {
      var c = teacherClassesFor(data.teachers[k], num);
      c.names.forEach(function (n) {
        if (otherNames.indexOf(n) === -1) otherNames.push(n);
      });
      otherPeriods.push(c.minPeriod);
    });

    var base = studentBase(data, num);
    base.mine = mine.names;
    base.other = otherNames.sort(cmpStr);
    base.minePeriod = mine.minPeriod;
    base.otherPeriod = Math.min.apply(null, otherPeriods);
    students.push(base);
  });

  students.sort(function (a, b) {
    return (
      a.minePeriod - b.minePeriod ||
      a.otherPeriod - b.otherPeriod ||
      String(a.lastName).localeCompare(String(b.lastName)) ||
      String(a.firstName).localeCompare(String(b.firstName))
    );
  });

  var them = teacherNamesFor(data, others);
  return {
    resolved: true,
    meLast: me.last,
    meFull: me.full,
    otherLast: them.last || String(param),
    otherFull: them.full || String(param),
    students: students,
  };
}

function buildSharedOverview(currentEmail) {
  return cachedBig('overview:' + username(currentEmail), function () {
    return buildSharedOverviewUncached(currentEmail);
  });
}

function buildSharedOverviewUncached(currentEmail) {
  var data = getData();
  var me = data.teachers[username(currentEmail)];
  if (!me) return { teachers: [] };

  var mine = myStudentNums(me);

  // other username -> [shared student numbers]
  var byTeacher = {};
  Object.keys(mine).forEach(function (num) {
    var st = data.students[num];
    if (!st) return;
    st.teachers.forEach(function (other) {
      if (other !== username(currentEmail)) {
        (byTeacher[other] = byTeacher[other] || []).push(num);
      }
    });
  });

  var teachers = Object.keys(byTeacher).map(function (other) {
    var ot = data.teachers[other];
    var nums = byTeacher[other];

    var students = nums
      .map(function (num) {
        return studentBase(data, num);
      })
      .sort(function (a, b) {
        return (
          String(a.lastName).localeCompare(String(b.lastName)) ||
          String(a.firstName).localeCompare(String(b.firstName))
        );
      });

    // Distinct individual course names this teacher teaches the shared students.
    var courseSet = {};
    nums.forEach(function (num) {
      Object.keys(ot.periods).forEach(function (p) {
        if (ot.periods[p].students.indexOf(num) !== -1) {
          ot.periods[p].courses.forEach(function (c) {
            courseSet[c] = true;
          });
        }
      });
    });

    return {
      key: other,
      last: ot.last,
      full: ot.full,
      courses: Object.keys(courseSet).sort(cmpStr),
      students: students,
    };
  });

  teachers.sort(function (a, b) {
    return (
      String(a.last).localeCompare(String(b.last)) ||
      String(a.full).localeCompare(String(b.full))
    );
  });

  return { teachers: teachers };
}

/* ------------------------------------------------------------------ */
/* Helpers over the normalized data                                    */
/* ------------------------------------------------------------------ */

function username(email) {
  return normalizeEmail(email).replace(/@.*$/, '');
}

// Concatenated display name for a section: "Biology / Biology H Period 2".
function sectionName(sec, period) {
  return sec.courses.join(' / ') + ' Period ' + period;
}

// A client student object (identity only) from the normalized students map.
function studentBase(data, num) {
  var s = data.students[num] || { studentNumber: num };
  return {
    studentNumber: s.studentNumber || num,
    firstName: s.firstName,
    lastName: s.lastName,
    nickname: s.nickname,
    grade: s.grade,
    gender: s.gender,
    fileId: s.fileId || '',
  };
}

// All of a teacher's student numbers across their periods, as a set.
function myStudentNums(teacher) {
  var nums = {};
  Object.keys(teacher.periods).forEach(function (p) {
    teacher.periods[p].students.forEach(function (num) {
      nums[num] = true;
    });
  });
  return nums;
}

// A student's full schedule across all teachers, sorted by period: one entry
// per section they sit in, as { period, course, teacher }.
function scheduleFor(data, num) {
  var st = data.students[num];
  if (!st) return [];
  var rows = [];
  st.teachers.forEach(function (u) {
    var t = data.teachers[u];
    if (!t) return;
    Object.keys(t.periods).forEach(function (p) {
      if (t.periods[p].students.indexOf(num) !== -1) {
        rows.push({ period: p, course: t.periods[p].courses.join(' / '), teacher: t.full });
      }
    });
  });
  rows.sort(function (a, b) {
    return periodNum(a.period) - periodNum(b.period) || cmpStr(a.course, b.course);
  });
  return rows;
}

// The class name(s) and earliest period a student sits in for one teacher.
function teacherClassesFor(teacher, num) {
  var names = [];
  var minP = Infinity;
  Object.keys(teacher.periods).forEach(function (p) {
    if (teacher.periods[p].students.indexOf(num) !== -1) {
      names.push(sectionName(teacher.periods[p], p));
      minP = Math.min(minP, periodNum(p));
    }
  });
  return { names: names.sort(cmpStr), minPeriod: minP };
}

// Resolve a ?shared-with= value to teacher usernames: match by username, last
// name, full name, or email (bare usernames get @berkeley.net appended).
function resolveTeachers(data, param) {
  var raw = normalizeEmail(param);
  var qualified = qualifyEmail(param);
  var out = [];
  Object.keys(data.teachers).forEach(function (u) {
    var t = data.teachers[u];
    if (
      t.email === qualified ||
      t.email === raw ||
      u === raw ||
      String(t.last || '').toLowerCase() === raw ||
      String(t.full || '').toLowerCase() === raw
    ) {
      out.push(u);
    }
  });
  return out;
}

// Distinct last name(s) and full name(s) for a set of teacher usernames.
function teacherNamesFor(data, usernames) {
  var lasts = [];
  var fulls = [];
  usernames.forEach(function (u) {
    var t = data.teachers[u];
    if (!t) return;
    if (t.last && lasts.indexOf(t.last) === -1) lasts.push(t.last);
    if (t.full && fulls.indexOf(t.full) === -1) fulls.push(t.full);
  });
  return { last: lasts.join(' / '), full: fulls.join(' / ') };
}

// "Last, First" -> "First Last"; other formats pass through.
function fullName(raw) {
  var parts = String(raw || '').split(',');
  if (parts.length === 2) return parts[1].trim() + ' ' + parts[0].trim();
  return String(raw || '').trim();
}

function cmpStr(a, b) {
  return String(a).localeCompare(String(b));
}

function periodNum(p) {
  var n = parseInt(p, 10);
  return isNaN(n) ? 9999 : n;
}

/**
 * (Re)build the `photos` tab by scanning CONFIG.DRIVE_FOLDER_ID for
 * <studentNumber>.jpg files, and the `missing photos` tab listing students
 * (personId, studentNumber) who have no photo. Run manually from the Apps
 * Script editor after uploading new photos.
 */
function refreshPhotoMap() {
  var folder = DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID);
  var files = folder.getFiles();
  var rows = [];
  var have = {};
  while (files.hasNext()) {
    var f = files.next();
    var m = f.getName().match(/^(\d+)\.jpe?g$/i);
    if (m) {
      rows.push([m[1], f.getId()]);
      have[m[1]] = true;
    }
  }
  rows.sort(function (a, b) {
    return Number(a[0]) - Number(b[0]);
  });

  var ss = spreadsheet();
  var sheet = ss.getSheetByName(PHOTOS_SHEET) || ss.insertSheet(PHOTOS_SHEET, ss.getNumSheets());
  sheet.clearContents();
  sheet.getRange(1, 1, 1, 2).setValues([['studentNumber', 'fileId']]);
  if (rows.length) sheet.getRange(2, 1, rows.length, 2).setValues(rows);
  Logger.log('Wrote ' + rows.length + ' photo rows to the "' + PHOTOS_SHEET + '" tab.');

  // Students (deduped — one row per section enrollment) with no photo file.
  var seen = {};
  var missing = [];
  readStudents().forEach(function (s) {
    var num = String(s.studentNumber || '');
    if (!num || have[num] || seen[num]) return;
    seen[num] = true;
    missing.push([String(s.personId || ''), num]);
  });
  missing.sort(function (a, b) {
    return Number(a[1]) - Number(b[1]);
  });

  var missingSheet =
    ss.getSheetByName(MISSING_PHOTOS_SHEET) || ss.insertSheet(MISSING_PHOTOS_SHEET, ss.getNumSheets());
  missingSheet.clearContents();
  missingSheet.getRange(1, 1, 1, 2).setValues([['personId', 'studentNumber']]);
  if (missing.length) missingSheet.getRange(2, 1, missing.length, 2).setValues(missing);
  Logger.log('Wrote ' + missing.length + ' rows to the "' + MISSING_PHOTOS_SHEET + '" tab.');

  clearCaches(); // new photos should show up immediately
}

/**
 * Return a student photo as a base64 data URL, read server-side (as the
 * deployer). Called via google.script.run for study-mode cards so photos load
 * even where the browser won't send Google cookies to drive.google.com
 * cross-site (e.g. Safari's tracking prevention on mobile). Returns '' on any
 * failure so the client just shows a blank card.
 */
function getPhoto(fileId) {
  if (!fileId) return '';
  var t0 = new Date().getTime();
  try {
    var blob = DriveApp.getFileById(fileId).getBlob(); // the full original (the source is small)
    var out = 'data:' + blob.getContentType() + ';base64,' + Utilities.base64Encode(blob.getBytes());
    logTime('getPhoto ' + fileId, t0);
    return out;
  } catch (err) {
    logTime('getPhoto ' + fileId + ' FAILED', t0);
    return '';
  }
}

/* ------------------------------------------------------------------ */
/* Staff directory                                                     */
/*                                                                     */
/* The BHS staff directory (STAFF_DIRECTORY_URL) is a public WordPress */
/* page whose whole directory is one server-rendered TablePress table: */
/* Picture | Last Name | First Name | Role | Contact (@berkeley.net).  */
/* refreshStaffDirectory() scrapes it into the `staff` tab; the app    */
/* serves that tab (never the live page) at ?staff. Photos stay on     */
/* bhs.berkeleyschools.net — the tab stores their public URLs.         */
/* ------------------------------------------------------------------ */

/**
 * (Re)build the `staff` tab by scraping the public staff directory page. Run
 * manually from the Apps Script editor after the school updates the directory
 * (start of each year at minimum).
 */
function refreshStaffDirectory() {
  importStaffHtml(fetchStaffPage());
}

/**
 * Admin upload of the directory page's saved HTML source, via the form at the
 * bottom of the Staff view — the no-tooling fallback for when the site's
 * firewall blocks Google's fetch servers (refreshStaffDirectory 403s): open
 * view-source: on the directory page, save it, upload the file.
 */
function uploadStaffDirectory(html, as) {
  var viewer = resolveViewer(as);
  if (!viewer || !viewer.isAdmin) throw new Error('Not authorized.');
  return { saved: importStaffHtml(String(html || '')) };
}

/**
 * Parse directory-page HTML and rewrite the `staff` tab from it; returns the
 * row count. Two guards, both throwing before the tab is touched: a row-count
 * floor (a page redesign must not silently empty the Staff section), and a
 * photo-URL sanity check — a browser's "Save Page As" copy rewrites img srcs
 * to local file paths, which would quietly break every photo; the page
 * *source* (view-source:) keeps the real URLs.
 */
function importStaffHtml(html) {
  var rows;
  try {
    rows = parseStaffDirectory(html);
  } catch (err) {
    // Not the raw page — maybe a saved copy of the view-source viewer or a
    // Safari webarchive. Recover the source if possible and try again.
    var source = recoverStaffSource(html); // throws its own error for webarchives
    try {
      rows = parseStaffDirectory(source);
    } catch (err2) {
      throw new Error(
        'No staff table found — is that the HTML source of the staff directory page? ' +
          'Open view-source:' +
          STAFF_DIRECTORY_URL +
          ' in a browser, then copy and paste it (or save it and upload the file).',
      );
    }
  }
  // The directory has ~300 rows; far fewer parsed means the page changed shape.
  if (rows.length < 200) {
    throw new Error(
      'Only parsed ' + rows.length + ' staff rows — did the page layout change? Tab left untouched.',
    );
  }
  var badPhotos = rows.filter(function (r) {
    return r.photoUrl && r.photoUrl.indexOf('/wp-content/') === -1;
  }).length;
  if (badPhotos > rows.length / 10) {
    throw new Error(
      badPhotos +
        ' rows have photo URLs that don\'t point at the directory site — was this file made ' +
        'with "Save Page As"? That rewrites the image links. Save the page source instead ' +
        '(open view-source: on the directory page, then save). Tab left untouched.',
    );
  }

  var ss = spreadsheet();
  var sheet = ss.getSheetByName(STAFF_SHEET) || ss.insertSheet(STAFF_SHEET, ss.getNumSheets());
  sheet.clearContents();
  sheet.getRange(1, 1, 1, 5).setValues([['lastName', 'firstName', 'role', 'email', 'photoUrl']]);
  sheet.getRange(2, 1, rows.length, 5).setValues(
    rows.map(function (r) {
      return [r.lastName, r.firstName, r.role, r.email, r.photoUrl];
    }),
  );
  Logger.log('Wrote ' + rows.length + ' staff rows to the "' + STAFF_SHEET + '" tab.');

  clearCaches(); // the new directory should show up immediately
  return rows.length;
}

/**
 * Fetch the staff directory page, retrying with backoff. The school site's
 * firewall intermittently 403s requests from Google's shared fetch servers
 * (IP reputation — the same request from a normal machine succeeds, and
 * UrlFetchApp's User-Agent can't be changed, so looking more like a browser
 * isn't an option). Each attempt can leave from a different address in
 * Google's pool, so retrying often gets through; when it doesn't, the local
 * fallback is scripts/scrape-staff.mjs (see DEPLOY.md).
 */
function fetchStaffPage() {
  var wait = 1000;
  for (var attempt = 1; ; attempt++) {
    var resp = UrlFetchApp.fetch(STAFF_DIRECTORY_URL, { muteHttpExceptions: true });
    var code = resp.getResponseCode();
    if (code === 200) return resp.getContentText();
    if (attempt >= 4) {
      throw new Error(
        'The staff directory returned HTTP ' + code + ' on ' + attempt + ' attempts — ' +
          "the site's firewall is probably blocking Google's servers right now. Try again " +
          'in a while, or scrape locally with scripts/scrape-staff.mjs (see DEPLOY.md).',
      );
    }
    Utilities.sleep(wait);
    wait *= 2;
  }
}

/**
 * Parse the directory page's TablePress table into row objects. Regexes, not a
 * DOM: Apps Script has no HTML parser and XmlService needs well-formed XML,
 * which this page isn't. Anchored to the known structure — the header row uses
 * <th> cells, so requiring five <td>s skips it.
 */
function parseStaffDirectory(html) {
  var table = html.match(/<table id="tablepress-\d+"[\s\S]*?<\/table>/);
  if (!table) throw new Error('No TablePress table in the staff directory page.');

  var out = [];
  var trRe = /<tr[^>]*>([\s\S]*?)<\/tr>/g;
  var tr;
  while ((tr = trRe.exec(table[0])) !== null) {
    var cells = [];
    var tdRe = /<td[^>]*>([\s\S]*?)<\/td>/g;
    var td;
    while ((td = tdRe.exec(tr[1])) !== null) cells.push(td[1]);
    if (cells.length !== 5) continue;
    out.push({
      lastName: cellText(cells[1]),
      firstName: cellText(cells[2]),
      role: cellText(cells[3]),
      email: staffContactEmail(cellText(cells[4])),
      photoUrl: staffPhotoUrl((cells[0].match(/src=['"]([^'"]+)['"]/) || [])[1]),
    });
  }
  return out;
}

/**
 * An uploaded "source" file isn't always the raw page. Saving a view-source:
 * tab saves the source *viewer* — a page that displays the source with the
 * markup HTML-escaped (Chrome adds line-number gutters too) — and Safari's
 * ⌘S default is a binary .webarchive. Reconstruct the raw source where
 * possible: take Chrome's line-content cells if present (skipping the line
 * numbers), else the whole document; then strip the viewer's own tags and
 * decode the escaping, leaving the original markup for parseStaffDirectory.
 */
function recoverStaffSource(html) {
  if (/^bplist00/.test(html)) {
    throw new Error(
      'That file is a Safari webarchive, not HTML. Copy the page source and paste it ' +
        'into the form instead (or save the page from Chrome or Firefox).',
    );
  }
  var lines = html.match(/<td class="line-content">[\s\S]*?<\/td>/g);
  return cellText(lines ? lines.join('\n') : html);
}

/**
 * A Contact cell -> email. Usually a bare username (qualifyEmail appends
 * @berkeley.net), but some cells append a phone extension ("danielbrownson
 * 644-4583") — the username is the first token. The few cells holding a full
 * (sometimes malformed) address pass through as-is; display-only either way.
 */
function staffContactEmail(cell) {
  var v = String(cell || '').trim();
  if (v.indexOf('@') === -1) v = v.split(/\s+/)[0];
  return qualifyEmail(v);
}

/** A table cell's plain text: tags stripped, common HTML entities decoded. */
function cellText(cell) {
  return String(cell || '')
    .replace(/<[^>]*>/g, '')
    .replace(/&#(\d+);/g, function (_, n) {
      return String.fromCharCode(Number(n));
    })
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&') // last, so "&amp;lt;" can't double-decode
    .trim();
}

/**
 * A row's photo URL: the page's relative src resolved to an absolute URL, or
 * '' for the shared "no photo yet" placeholder image (rendered as initials,
 * like a student without a photo).
 */
function staffPhotoUrl(src) {
  if (!src || /\/pp\.png$/i.test(src)) return '';
  if (/^https?:\/\//i.test(src)) return src;
  var origin = STAFF_DIRECTORY_URL.match(/^https?:\/\/[^\/]+/)[0];
  return src.charAt(0) === '/' ? origin + src : STAFF_DIRECTORY_URL + src;
}

/** Staff rows from the `staff` tab ([] until refreshStaffDirectory has run). */
function readStaff() {
  var sheet = spreadsheet().getSheetByName(STAFF_SHEET);
  return sheet ? sheetToObjects(sheet) : [];
}

/**
 * The client staff model: the `staff` tab, with each row's fields replaced by
 * the owner's overrides where present, sorted by last then first name. The
 * same for every viewer (the source page is public), so cached once under a
 * single key — chunked, since ~300 rows of JSON runs close to CacheService's
 * per-key limit.
 */
function buildStaffModel() {
  return cachedBig('staff', function () {
    var overrides = readStaffOverrides();
    var staff = readStaff().map(function (r) {
      var o = overrides[normalizeEmail(r.email)];
      return {
        firstName: String(((o && o.firstName) || r.firstName) || ''),
        lastName: String(((o && o.lastName) || r.lastName) || ''),
        role: String(((o && o.role) || r.role) || ''),
        email: String(r.email || ''),
        // A self-taken photo (a data URL in the overrides tab) wins over the
        // scraped directory URL; both are plain <img> srcs to the client.
        photoUrl: String(((o && o.photo) || r.photoUrl) || ''),
        // The edit form's Reset button (fields) and Remove photo button key
        // off these.
        overridden: !!(o && (o.firstName || o.lastName || o.role)),
        photoOverride: !!(o && o.photo),
        // Opted out of the Staff section — publicStaffModel drops these.
        optOut: !!(o && String(o.optOut || '').trim()),
      };
    });
    staff.sort(function (a, b) {
      return cmpStr(a.lastName, b.lastName) || cmpStr(a.firstName, b.firstName);
    });
    return { staff: staff };
  });
}

/**
 * The staff model minus opted-out entries — what every viewer-facing route
 * serves, so an opted-out member appears nowhere in anyone's UI (or payload).
 */
function publicStaffModel() {
  return {
    staff: buildStaffModel().staff.filter(function (p) {
      return !p.optOut;
    }),
  };
}

/**
 * The viewer's own merged entry (or null), for the ?staff-edit form. Looked
 * up in the full model, not the public one, so someone who has opted out
 * still sees their entry and can opt back in.
 */
function staffEntryFor(email) {
  var target = normalizeEmail(email);
  var match = null;
  buildStaffModel().staff.forEach(function (p) {
    if (!match && normalizeEmail(p.email) === target) match = p;
  });
  return match;
}

/**
 * Staff self-edits from the `staff overrides` tab, keyed by normalized email.
 * A separate tab from the scraped `staff` one so refreshStaffDirectory can
 * rewrite that wholesale without losing anyone's corrections. A non-empty
 * override cell wins over the scraped value, field by field.
 */
function readStaffOverrides() {
  var sheet = spreadsheet().getSheetByName(STAFF_OVERRIDES_SHEET);
  var map = {};
  if (sheet) {
    sheetToObjects(sheet).forEach(function (r) {
      var email = normalizeEmail(r.email);
      if (email) map[email] = r;
    });
  }
  return map;
}

/**
 * Save the calling user's corrections to their own staff entry (called via
 * google.script.run from the ?staff-edit form). `as` carries the client's
 * ?as= so an admin can edit on someone's behalf (resolveViewer re-checks
 * admin-ness; a non-admin's `as` is ignored). Values equal to the scraped row
 * aren't stored — the entry keeps tracking the directory until something
 * actually differs, and a save that differs in nothing drops any existing
 * override row.
 */
function saveStaffOverride(fields, as) {
  var viewer = resolveViewer(as);
  if (!viewer) throw new Error('Not authorized.');
  var email = viewer.effective;

  var base = findStaffRow(email);
  if (!base) throw new Error('No staff directory entry for ' + email + '.');

  var f = fields || {};
  var firstName = String(f.firstName || '').trim();
  var lastName = String(f.lastName || '').trim();
  var role = String(f.role || '').trim();
  if (!firstName || !lastName) throw new Error('First and last name are both required.');

  var changes = {
    firstName: firstName === String(base.firstName || '').trim() ? '' : firstName,
    lastName: lastName === String(base.lastName || '').trim() ? '' : lastName,
    role: role === String(base.role || '').trim() ? '' : role,
  };
  updateStaffOverride(email, changes);
  dropBigCache('staff');
  return { overridden: !!(changes.firstName || changes.lastName || changes.role) };
}

/**
 * Reset the calling user's name/role fields to the directory values (a photo
 * override, which has its own Remove control, is left alone). Returns the
 * scraped values so the form can show them in place — it can't navigate or
 * reload from an async handler (the sandbox blocks non-gesture top
 * navigation; see renderStaffEdit).
 */
function deleteStaffOverride(as) {
  var viewer = resolveViewer(as);
  if (!viewer) throw new Error('Not authorized.');
  updateStaffOverride(viewer.effective, { firstName: '', lastName: '', role: '' });
  dropBigCache('staff');
  var base = findStaffRow(viewer.effective);
  return base
    ? {
        firstName: String(base.firstName || ''),
        lastName: String(base.lastName || ''),
        role: String(base.role || ''),
      }
    : null;
}

/**
 * Save a self-taken photo from the ?staff-edit camera into the caller's
 * override row. The photo is a 172x228 JPEG data URL stored right in the
 * sheet cell (~15-25KB, comfortably under the 50,000-character cell cap) and
 * wins over the scraped photoUrl in the model.
 */
function saveStaffPhoto(dataUrl, as) {
  var viewer = resolveViewer(as);
  if (!viewer) throw new Error('Not authorized.');
  if (!findStaffRow(viewer.effective)) {
    throw new Error('No staff directory entry for ' + viewer.effective + '.');
  }
  var photo = String(dataUrl || '');
  if (!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(photo)) {
    throw new Error('Not a JPEG data URL.');
  }
  if (photo.length > 49000) {
    throw new Error('That photo is too big to store — expected a 172x228 JPEG.');
  }
  updateStaffOverride(viewer.effective, { photo: photo });
  dropBigCache('staff');
  return true;
}

/**
 * Drop the calling user's self-taken photo so their entry shows the directory
 * photo again. Returns the scraped photoUrl for the form to swap in.
 */
function removeStaffPhoto(as) {
  var viewer = resolveViewer(as);
  if (!viewer) throw new Error('Not authorized.');
  updateStaffOverride(viewer.effective, { photo: '' });
  dropBigCache('staff');
  var base = findStaffRow(viewer.effective);
  return { photoUrl: base ? String(base.photoUrl || '') : '' };
}

/**
 * Opt the caller out of (or back into) the Staff section. Stored in the
 * `optOut` column of their overrides row ('yes', or cleared); opted-out
 * entries are dropped from publicStaffModel so they appear nowhere in the
 * UI, while the ?staff-edit page (fed from the full model) still shows their
 * entry so they can return. Their other overrides are kept either way.
 */
function saveStaffOptOut(optOut, as) {
  var viewer = resolveViewer(as);
  if (!viewer) throw new Error('Not authorized.');
  if (!findStaffRow(viewer.effective)) {
    throw new Error('No staff directory entry for ' + viewer.effective + '.');
  }
  updateStaffOverride(viewer.effective, { optOut: optOut ? 'yes' : '' });
  dropBigCache('staff');
  return { optOut: !!optOut };
}

/** The scraped `staff` tab row for an email, or null. */
function findStaffRow(email) {
  var target = normalizeEmail(email);
  var found = null;
  readStaff().forEach(function (r) {
    if (!found && normalizeEmail(r.email) === target) found = r;
  });
  return found;
}

var STAFF_OVERRIDE_FIELDS = ['firstName', 'lastName', 'role', 'photo', 'optOut'];

/**
 * Merge `changes` (any subset of STAFF_OVERRIDE_FIELDS; '' clears a field,
 * an absent key leaves it alone) into email's row of the `staff overrides`
 * tab, dropping the row entirely when nothing is left overridden.
 * A read-modify-write of the whole tab — it's small — so a script lock
 * serializes concurrent saves (same pattern as rewriteLists).
 */
function updateStaffOverride(email, changes) {
  var target = normalizeEmail(email);
  var lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    var ss = spreadsheet();
    var sheet =
      ss.getSheetByName(STAFF_OVERRIDES_SHEET) ||
      ss.insertSheet(STAFF_OVERRIDES_SHEET, ss.getNumSheets());
    var existing = null;
    var others = sheetToObjects(sheet).filter(function (r) {
      if (normalizeEmail(r.email) === target) {
        existing = r;
        return false;
      }
      return true;
    });

    var merged = {};
    var any = false;
    STAFF_OVERRIDE_FIELDS.forEach(function (f) {
      var has = Object.prototype.hasOwnProperty.call(changes, f);
      merged[f] = String((has ? changes[f] : existing && existing[f]) || '');
      if (merged[f]) any = true;
    });

    var rows = others.map(function (r) {
      return [String(r.email)].concat(
        STAFF_OVERRIDE_FIELDS.map(function (f) {
          return String(r[f] || '');
        }),
      );
    });
    if (any) {
      rows.push(
        [target].concat(
          STAFF_OVERRIDE_FIELDS.map(function (f) {
            return merged[f];
          }),
        ),
      );
    }
    var width = 1 + STAFF_OVERRIDE_FIELDS.length;
    sheet.clearContents();
    sheet.getRange(1, 1, 1, width).setValues([['email'].concat(STAFF_OVERRIDE_FIELDS)]);
    if (rows.length) sheet.getRange(2, 1, rows.length, width).setValues(rows);
  } finally {
    lock.releaseLock();
  }
}

/* ------------------------------------------------------------------ */
/* Custom lists (admin-only)                                           */
/*                                                                     */
/* Admins upload (or paste) a plain-text list of student numbers, one  */
/* per line — or TSV rows: student number first, other columns kept as */
/* extra card-back lines. Stored in the `lists` tab as one row per     */
/* (teacherEmail, listName, studentNumber, extra) and served back as   */
/* model.lists, studied like a class. Saving replaces any same-named   */
/* list. Admin-only because a list can name any student in the roster, */
/* not just the uploader's own.                                        */
/* ------------------------------------------------------------------ */

/**
 * Save (or replace) a custom list for the calling teacher. `text` is the
 * uploaded file or pasted numbers, one student number per line — or TSV rows
 * whose first column is the student number, with the remaining columns kept
 * as extra lines for the back of the student's card. Lines that
 * aren't in the roster (or aren't numbers at all) are skipped and reported
 * back so the client can warn about them. Called via google.script.run; `as`
 * is the client's ?as= param so an admin's edits land under the impersonated
 * user (resolveViewer re-checks admin-ness — a non-admin's `as` is ignored).
 * Admin-only: a list can name any student in the roster, so the effective
 * email must itself be an admin (matching listsFor's read-side gate).
 */
function saveList(name, text, as) {
  var viewer = resolveViewer(as);
  if (!viewer || !readAdmins().has(viewer.effective)) throw new Error('Not authorized.');
  var listName = String(name || '').trim();
  if (!listName) throw new Error('The list needs a name.');

  var lines = String(text || '')
    .split(/\r?\n/)
    .map(function (s) {
      return s.trim();
    })
    .filter(function (s) {
      return s !== '';
    });

  var data = getData();
  var seen = {};
  var entries = [];
  var unknown = [];
  var invalid = [];
  lines.forEach(function (line) {
    var fields = line.split('\t').map(function (s) {
      return s.trim();
    });
    var num = fields[0];
    var extra = fields.slice(1).filter(function (s) {
      return s !== '';
    });
    if (!/^\d+$/.test(num)) {
      if (invalid.indexOf(line) === -1) invalid.push(line);
    } else if (!data.students[num]) {
      if (unknown.indexOf(num) === -1) unknown.push(num);
    } else if (!seen[num]) {
      seen[num] = true;
      entries.push({ num: num, extra: extra });
    }
  });
  if (!entries.length) {
    throw new Error('No roster student numbers in the upload — is that the right file?');
  }

  rewriteLists(viewer.effective, listName, entries);
  invalidateModel(viewer.effective);
  return { saved: entries.length, unknown: unknown, invalid: invalid };
}

/** Delete one of the calling admin's custom lists (same gate as saveList). */
function deleteList(name, as) {
  var viewer = resolveViewer(as);
  if (!viewer || !readAdmins().has(viewer.effective)) throw new Error('Not authorized.');
  rewriteLists(viewer.effective, String(name || '').trim(), []);
  invalidateModel(viewer.effective);
  return true;
}

/**
 * Rewrite the `lists` tab with (email, name)'s rows replaced by `entries`
 * ({ num, extra } objects; empty = delete the list). The `extra` column holds
 * a row's spare TSV fields as a JSON array (blank when there are none). A
 * read-modify-write of the whole tab — it's small — so a script lock
 * serializes concurrent saves.
 */
function rewriteLists(email, name, entries) {
  var target = qualifyEmail(email);
  var lock = LockService.getScriptLock();
  lock.waitLock(30000);
  try {
    var ss = spreadsheet();
    var sheet = ss.getSheetByName(LISTS_SHEET) || ss.insertSheet(LISTS_SHEET, ss.getNumSheets());
    var rows = sheetToObjects(sheet)
      .filter(function (r) {
        return !(qualifyEmail(r.teacherEmail) === target && String(r.listName || '').trim() === name);
      })
      .map(function (r) {
        return [
          String(r.teacherEmail),
          String(r.listName),
          String(r.studentNumber),
          r.extra == null ? '' : String(r.extra),
        ];
      });
    entries.forEach(function (e) {
      rows.push([target, name, e.num, e.extra.length ? JSON.stringify(e.extra) : '']);
    });
    sheet.clearContents();
    sheet.getRange(1, 1, 1, 4).setValues([['teacherEmail', 'listName', 'studentNumber', 'extra']]);
    if (rows.length) sheet.getRange(2, 1, rows.length, 4).setValues(rows);
  } finally {
    lock.releaseLock();
  }
}

/* ------------------------------------------------------------------ */
/* Spreadsheet helpers                                                 */
/* ------------------------------------------------------------------ */

function spreadsheet() {
  return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);
}

/** Student rows come from the `rosters` tab of the spreadsheet. */
function readStudents() {
  var t0 = new Date().getTime();
  var sheet = spreadsheet().getSheetByName(ROSTERS_SHEET);
  if (!sheet) {
    throw new Error('No "' + ROSTERS_SHEET + '" tab in the spreadsheet — rename the roster tab.');
  }
  var rows = sheetToObjects(sheet);
  logTime('readStudents (' + rows.length + ' rows)', t0);
  return rows;
}

/**
 * A `lists` tab `extra` cell -> array of card-back lines. rewriteLists stores
 * a JSON array, but a hand-edited cell of plain text works too (one line).
 */
function parseExtra(cell) {
  var raw = cell == null ? '' : String(cell).trim();
  if (!raw) return [];
  try {
    var parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      return parsed.map(function (x) {
        return String(x);
      });
    }
  } catch (err) {
    // fall through — treat the cell as literal text
  }
  return [raw];
}

/** All custom-list rows from the `lists` tab ([] until the first list is saved). */
function readLists() {
  var sheet = spreadsheet().getSheetByName(LISTS_SHEET);
  return sheet ? sheetToObjects(sheet) : [];
}

/** studentNumber -> fileId from the `photos` tab. */
function readPhotoMap() {
  var t0 = new Date().getTime();
  var sheet = spreadsheet().getSheetByName(PHOTOS_SHEET);
  var map = {};
  if (sheet) {
    sheetToObjects(sheet).forEach(function (r) {
      if (r.studentNumber !== '' && r.studentNumber != null) {
        map[String(r.studentNumber)] = String(r.fileId);
      }
    });
  }
  logTime('readPhotoMap (' + Object.keys(map).length + ' photos)', t0);
  return map;
}

/**
 * Lowercased Set of admin emails from the `admins` tab. Reads every cell and
 * keeps anything that resolves to an email — bare usernames get @berkeley.net
 * appended — so the tab can be a plain list of names or full addresses, with or
 * without a header row. (A stray label like "email" becomes
 * "email@berkeley.net", which matches nobody's login and is harmless.)
 */
function readAdmins() {
  var emails = cached('admins', function () {
    var t0 = new Date().getTime();
    var sheet = spreadsheet().getSheetByName(ADMINS_SHEET);
    var out = [];
    if (sheet) {
      sheet.getDataRange().getValues().forEach(function (row) {
        row.forEach(function (cell) {
          var email = qualifyEmail(cell);
          if (isEmailShaped(email)) out.push(email);
        });
      });
    }
    logTime('readAdmins', t0);
    return out;
  });
  return new Set(emails);
}

/** Read a sheet into an array of objects keyed by the header row. */
function sheetToObjects(sheet) {
  var values = sheet.getDataRange().getValues();
  if (values.length < 2) return [];
  var headers = values[0].map(function (h) {
    return String(h).trim();
  });
  return values
    .slice(1)
    .filter(function (row) {
      return row.some(function (c) {
        return c !== '' && c !== null;
      });
    })
    .map(function (row) {
      var o = {};
      headers.forEach(function (h, i) {
        o[h] = row[i];
      });
      return o;
    });
}

/* ------------------------------------------------------------------ */
/* Small utilities                                                     */
/* ------------------------------------------------------------------ */

function slugify(s) {
  return String(s)
    .replace(/\s+/g, '-')
    .replace(/[^-\w]/g, '')
    .toLowerCase();
}

function normalizeEmail(s) {
  return String(s || '').trim().toLowerCase();
}

// Normalize an email or bare username: trim + lowercase, and append
// @berkeley.net when no domain is given, so "peterseibel" becomes
// "peterseibel@berkeley.net". Used for both the admins tab and ?as=.
function qualifyEmail(s) {
  var v = normalizeEmail(s);
  if (!v) return '';
  if (v.indexOf('@') === -1) v = v + '@berkeley.net';
  return v;
}

function isEmailShaped(s) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}

function isBerkeleyStaff(email) {
  return /@berkeley\.net$/.test(email);
}

/**
 * Resolve the calling user for a request or google.script.run call: the
 * signed-in user (null if not @berkeley.net staff), their admin status, and
 * the effective email after honoring an admin's ?as= impersonation (a
 * non-admin's `as` is ignored). The one gate shared by doGet and the
 * list-editing endpoints — identity always comes from the session, never the
 * client.
 */
function resolveViewer(asParam) {
  var actual = normalizeEmail(Session.getActiveUser().getEmail());
  if (!isBerkeleyStaff(actual)) return null;
  var isAdmin = readAdmins().has(actual);
  var effective = (isAdmin && asParam ? qualifyEmail(asParam) : '') || actual;
  return {
    actual: actual,
    effective: effective,
    impersonating: effective !== actual,
    isAdmin: isAdmin,
  };
}

function jsonForScript(obj) {
  // Safe to inline inside a <script> via <?!= ?>: escape "<" so a value can
  // never terminate the script element.
  return JSON.stringify(obj).replace(/</g, '\\u003c');
}

function page(template) {
  var t0 = new Date().getTime();
  var out = template
    .evaluate()
    .setTitle('Facecards')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
  logTime('page.evaluate', t0);
  return out;
}

function getBaseUrl() {
  try {
    return ScriptApp.getService().getUrl() || '';
  } catch (err) {
    return '';
  }
}

// Timing helper — logs to Cloud Logging (visible in the Apps Script Executions
// panel and Logs Explorer). Call with a start time from new Date().getTime().
function logTime(label, t0) {
  console.log(label + ': ' + (new Date().getTime() - t0) + ' ms');
}

/* ------------------------------------------------------------------ */
/* Caching                                                             */
/*                                                                     */
/* The roster sheet is large (tens of thousands of rows), so reading   */
/* it on every page load is slow. We memoize derived, per-viewer data  */
/* in the script cache. A version token (a script property) lets us    */
/* invalidate everything at once — bumped by refreshPhotoMap and by    */
/* clearCaches() (run the latter after editing the roster).            */
/* ------------------------------------------------------------------ */

var CACHE_TTL = 21600; // seconds (6h — the max; version-busted on data edits)
var _cacheVersion = null;

function cacheVersion() {
  if (_cacheVersion === null) {
    _cacheVersion = PropertiesService.getScriptProperties().getProperty('CACHE_VERSION') || '0';
  }
  return _cacheVersion;
}

function vkey(key) {
  return 'v' + cacheVersion() + ':' + key;
}

/** Memoize a small (<100KB) JSON-able value in the script cache. */
function cached(key, fn) {
  var cache = CacheService.getScriptCache();
  var full = vkey(key);
  var hit = cache.get(full);
  if (hit !== null) {
    console.log('cache hit: ' + key);
    return JSON.parse(hit);
  }
  var val = fn();
  var json = JSON.stringify(val);
  if (json.length < 100000) {
    cache.put(full, json, CACHE_TTL);
  } else {
    console.log('cache skip (' + json.length + ' bytes): ' + key);
  }
  return val;
}

var CHUNK_SIZE = 90000; // under CacheService's 100KB-per-key limit

/** Memoize a large JSON-able value, split across chunk keys. */
function cachedBig(key, fn) {
  var t0 = new Date().getTime();
  var raw = readChunks(key);
  if (raw !== null) {
    var val = JSON.parse(raw);
    logTime('cache hit (big) ' + key + ' (' + raw.length + ' bytes)', t0);
    return val;
  }
  var built = fn();
  writeChunks(key, JSON.stringify(built));
  return built;
}

function readChunks(key) {
  var cache = CacheService.getScriptCache();
  var nStr = cache.get(vkey(key + ':n'));
  if (!nStr) return null;
  var n = Number(nStr);
  var keys = [];
  for (var i = 0; i < n; i++) keys.push(vkey(key + ':' + i));
  var parts = cache.getAll(keys);
  var out = '';
  for (var j = 0; j < n; j++) {
    var piece = parts[vkey(key + ':' + j)];
    if (piece == null) return null; // a chunk was evicted -> treat as a miss
    out += piece;
  }
  return out;
}

function writeChunks(key, str) {
  var cache = CacheService.getScriptCache();
  var n = Math.ceil(str.length / CHUNK_SIZE) || 1;
  for (var i = 0; i < n; i++) {
    cache.put(vkey(key + ':' + i), str.substr(i * CHUNK_SIZE, CHUNK_SIZE), CACHE_TTL);
  }
  cache.put(vkey(key + ':n'), String(n), CACHE_TTL);
  console.log('cached big: ' + key + ' (' + n + ' chunks, ' + str.length + ' bytes)');
}

/**
 * The whole roster, normalized once and cached (in chunks): students deduped
 * into a map, teachers into a map of period -> { room, courses, student
 * numbers }, and each student carrying the usernames of their teachers (so
 * "shared" is a cheap derive). Every viewer's view is a lookup into this, not a
 * scan of the sheet.
 */
function getData() {
  return cachedBig('data', buildData);
}

function buildData() {
  var t0 = new Date().getTime();
  var rows = readStudents();
  var photos = readPhotoMap();

  var students = {};
  var teachers = {};

  rows.forEach(function (s) {
    var num = String(s.studentNumber);
    var email = normalizeEmail(s.teacherEmail);
    if (!num || !email) return;
    var user = email.replace(/@.*$/, '');
    var period = String(s.period);

    if (!students[num]) {
      // A nickname that just repeats the first name is roster noise, not a
      // real nickname -- treat the student as having none.
      var nickname = String(s.nickname || '').trim();
      if (nickname.toLowerCase() === String(s.firstName || '').trim().toLowerCase()) {
        nickname = '';
      }
      students[num] = {
        studentNumber: num,
        firstName: s.firstName,
        middleName: s.middleName,
        lastName: s.lastName,
        nickname: nickname,
        grade: s.grade,
        gender: s.gender,
        fileId: photos[num] || '',
        teachers: [],
      };
    }
    if (students[num].teachers.indexOf(user) === -1) students[num].teachers.push(user);

    if (!teachers[user]) {
      teachers[user] = {
        email: email,
        last: String(s.teacherName || '').replace(/,.*$/, '').trim(),
        full: fullName(s.teacherName),
        periods: {},
      };
    }
    var periods = teachers[user].periods;
    if (!periods[period]) {
      periods[period] = { room: String(s.room || ''), courses: [], students: [] };
    }
    var sec = periods[period];
    var course = String(s.course || '').trim();
    if (course && sec.courses.indexOf(course) === -1) sec.courses.push(course);
    if (sec.students.indexOf(num) === -1) sec.students.push(num);
  });

  Object.keys(teachers).forEach(function (u) {
    var periods = teachers[u].periods;
    Object.keys(periods).forEach(function (p) {
      periods[p].courses.sort(cmpStr);
    });
  });

  logTime(
    'buildData (' +
      Object.keys(students).length +
      ' students, ' +
      Object.keys(teachers).length +
      ' teachers)',
    t0,
  );
  return { students: students, teachers: teachers };
}

/**
 * Drop one chunked cachedBig entry (its ':n' counter and chunk keys) so the
 * next read rebuilds it. Targeted invalidation for small edits — bumping the
 * global version (clearCaches) would needlessly throw away the expensive
 * roster blob and every viewer's model.
 */
function dropBigCache(key) {
  var cache = CacheService.getScriptCache();
  var nStr = cache.get(vkey(key + ':n'));
  if (nStr === null) return;
  var keys = [vkey(key + ':n')];
  for (var i = 0; i < Number(nStr); i++) keys.push(vkey(key + ':' + i));
  cache.removeAll(keys);
}

/** Drop one viewer's cached model. Used after custom-list edits. */
function invalidateModel(email) {
  dropBigCache('model:' + username(email));
}

/** Invalidate all cached models/admins. Run after editing the roster. */
function clearCaches() {
  var props = PropertiesService.getScriptProperties();
  var next = String(Number(props.getProperty('CACHE_VERSION') || '0') + 1);
  props.setProperty('CACHE_VERSION', next);
  _cacheVersion = next;
  console.log('Caches cleared (version ' + next + ').');
}

/**
 * Rebuild the normalized data blob so users never pay the cold ~5–7s build.
 * Bumps the version (invalidating stale per-viewer caches) then warms the blob.
 * Put this on a time-driven trigger (e.g. hourly) via the Apps Script editor's
 * Triggers panel.
 */
function warmData() {
  var t0 = new Date().getTime();
  clearCaches();
  getData(); // reads the sheet and caches the fresh blob under the new version
  logTime('warmData', t0);
}
