/**
 * Facecards — Google Apps Script web app.
 *
 * Data lives in the spreadsheet named by CONFIG.SPREADSHEET_ID:
 *   - first tab  : one row per student/section enrollment (headers include
 *                  studentNumber, firstName, lastName, nickname, period, course,
 *                  gender, teacherEmail, grade, teacherName, ...)
 *   - `photos` tab : studentNumber -> Drive fileId, generated by refreshPhotoMap()
 *   - `admins` tab : one admin email per row (header `email`)
 *
 * Photos are surfaced as drive.google.com/thumbnail URLs from the folder named
 * by CONFIG.DRIVE_FOLDER_ID (shared view-only with the domain).
 *
 * Access: deployed with webapp.access DOMAIN + executeAs USER_DEPLOYING, so the
 * app reads the deployer's private spreadsheet while only domain users can open
 * it. doGet further restricts to exact @berkeley.net addresses (excluding
 * students at @students.berkeley.net) and scopes each viewer to their own
 * sections. Admins (from the `admins` tab) may impersonate any user via ?as=.
 */

var PHOTOS_SHEET = 'photos';
var ADMINS_SHEET = 'admins';

function doGet(e) {
  e = e || {};
  var params = e.parameter || {};

  var actual = normalizeEmail(Session.getActiveUser().getEmail());

  if (!isBerkeleyStaff(actual)) {
    return HtmlService.createHtmlOutput(
      '<p style="font-family:system-ui,sans-serif;margin:2rem">Not authorized.</p>'
    ).setTitle('Facecards');
  }

  var isAdmin = readAdmins().has(actual);
  var asParam = isAdmin && params.as ? qualifyEmail(params.as) : '';
  var effective = asParam || actual;
  var impersonating = effective !== actual;

  var ctx = {
    actual: actual,
    effective: effective,
    impersonating: impersonating,
    isAdmin: isAdmin,
    baseUrl: getBaseUrl(),
  };

  // Shared-with view: a table of students the viewer shares with another teacher.
  if (params['shared-with']) {
    var st = HtmlService.createTemplateFromFile('index');
    st.modelJson = jsonForScript({ teacherLast: '', classes: {} });
    st.routeJson = jsonForScript({ mode: 'shared', scope: '', id: '' });
    st.sharedJson = jsonForScript(buildSharedModel(effective, String(params['shared-with'])));
    st.ctxJson = jsonForScript(ctx);
    return page(st);
  }

  // Shared overview: every teacher the viewer shares students with, each with a
  // face grid linking to that teacher's shared-with page.
  if (params.shared !== undefined) {
    var ot = HtmlService.createTemplateFromFile('index');
    ot.modelJson = jsonForScript({ teacherLast: '', classes: {} });
    ot.routeJson = jsonForScript({ mode: 'shared-overview', scope: '', id: '' });
    ot.sharedJson = jsonForScript(buildSharedOverview(effective));
    ot.ctxJson = jsonForScript(ctx);
    return page(ot);
  }

  var model = buildModel(effective);

  // No sections for this viewer -> landing page.
  if (Object.keys(model.classes).length === 0) {
    var landing = HtmlService.createTemplateFromFile('landing');
    landing.ctx = ctx;
    return page(landing);
  }

  var mode;
  if (params.mode === 'learn' || params.mode === 'review') {
    mode = params.mode; // study deep link
  } else if (params.learn !== undefined) {
    mode = 'grid'; // ?learn -> the class face grids
  } else {
    mode = 'menu'; // default -> two-box menu
  }
  var route = {
    mode: mode,
    scope: params.scope || '', // '' | class | all
    id: params.id || '', // class slug
  };

  var t = HtmlService.createTemplateFromFile('index');
  t.modelJson = jsonForScript(model);
  t.routeJson = jsonForScript(route);
  t.sharedJson = jsonForScript(null);
  t.ctxJson = jsonForScript(ctx);
  return page(t);
}

/** Included by index.html / landing.html to inline the client partials. */
function include(name) {
  return HtmlService.createHtmlOutputFromFile(name).getContent();
}

/**
 * Build the data model scoped to one viewer email: only the sections whose
 * teacherEmail matches. Returns { teacherLast, classes } where classes is keyed
 * by slug and each student is joined to its photo fileId.
 */
function buildModel(email) {
  var rows = readStudents().filter(function (r) {
    return normalizeEmail(r.teacherEmail) === email;
  });
  var photos = readPhotoMap();

  var classes = {};
  var teacherLast = '';

  // A "class" is the group of students a teacher sees together — one room at one
  // period. Several course codes can share that slot (e.g. Biology + Biology H),
  // so we key on room + period and collect the distinct course names for the
  // display name.
  rows.forEach(function (s) {
    var lastName = String(s.teacherName || '').replace(/,.*$/, '');
    var teacher = String(s.teacherEmail || '').replace(/@.*$/, '').toLowerCase();
    var slug = slugify(s.room + '-p-' + s.period + '-' + teacher);
    teacherLast = lastName;

    if (!(slug in classes)) {
      classes[slug] = {
        slug: slug,
        room: s.room,
        period: s.period,
        teacherLast: lastName,
        courses: [], // distinct course names sharing this room + period
        students: [],
      };
    }
    var c = classes[slug];
    var course = String(s.course || '');
    if (course && c.courses.indexOf(course) === -1) c.courses.push(course);
    c.students.push({
      studentNumber: String(s.studentNumber),
      firstName: s.firstName,
      lastName: s.lastName,
      nickname: s.nickname,
      grade: s.grade,
      gender: s.gender,
      course: s.course,
      period: s.period,
      fileId: photos[String(s.studentNumber)] || '',
    });
  });

  // Name each class from its course list: "Biology / Biology H Period 2".
  Object.keys(classes).forEach(function (slug) {
    var c = classes[slug];
    c.courses.sort(function (a, b) {
      return a.localeCompare(b);
    });
    c.name = c.courses.join(' / ') + ' Period ' + c.period;
  });

  return { teacherLast: teacherLast, classes: classes };
}

/**
 * Build the "shared with" table model: students that the current teacher and a
 * named other teacher both teach. For each such student we return their photo,
 * identity info, the current teacher's class(es), and the other teacher's
 * class(es), sorted by the current teacher's period, then the other's, then
 * last name, then first name. Returns { resolved: false, param } when the other
 * teacher can't be found.
 */
function buildSharedModel(currentEmail, param) {
  var rows = readStudents();
  var photos = readPhotoMap();

  var otherEmails = resolveTeachers(rows, param);
  otherEmails.delete(currentEmail); // sharing "with yourself" is meaningless
  if (otherEmails.size === 0) {
    return { resolved: false, param: param };
  }

  // Group every row into room+period classes (per teacher) and track, per
  // student, which classes they're in. This spans the whole roster, not just
  // the viewer's sections.
  var classIndex = {}; // slug -> { name, period, teacherEmail, courses }
  var info = {}; // studentNumber -> identity fields
  var slugsFor = {}; // studentNumber -> Set(slug)

  rows.forEach(function (s) {
    var num = String(s.studentNumber);
    var teacher = normalizeEmail(s.teacherEmail);
    var local = teacher.replace(/@.*$/, '');
    var slug = slugify(s.room + '-p-' + s.period + '-' + local);

    if (!classIndex[slug]) {
      classIndex[slug] = { period: s.period, teacherEmail: teacher, courses: [] };
    }
    var course = String(s.course || '');
    if (course && classIndex[slug].courses.indexOf(course) === -1) {
      classIndex[slug].courses.push(course);
    }

    if (!info[num]) {
      info[num] = {
        studentNumber: num,
        firstName: s.firstName,
        lastName: s.lastName,
        nickname: s.nickname,
        grade: s.grade,
        gender: s.gender,
        fileId: photos[num] || '',
      };
    }
    (slugsFor[num] = slugsFor[num] || new Set()).add(slug);
  });

  Object.keys(classIndex).forEach(function (slug) {
    var c = classIndex[slug];
    c.courses.sort(function (a, b) { return a.localeCompare(b); });
    c.name = c.courses.join(' / ') + ' Period ' + c.period;
  });

  var students = [];
  Object.keys(slugsFor).forEach(function (num) {
    var mine = [];
    var other = [];
    slugsFor[num].forEach(function (slug) {
      var c = classIndex[slug];
      if (c.teacherEmail === currentEmail) mine.push(c);
      else if (otherEmails.has(c.teacherEmail)) other.push(c);
    });
    if (mine.length && other.length) {
      var i = info[num];
      students.push({
        studentNumber: num,
        firstName: i.firstName,
        lastName: i.lastName,
        nickname: i.nickname,
        grade: i.grade,
        gender: i.gender,
        fileId: i.fileId,
        mine: classNames(mine),
        other: classNames(other),
        minePeriod: minPeriod(mine),
        otherPeriod: minPeriod(other),
      });
    }
  });

  students.sort(function (a, b) {
    return (
      a.minePeriod - b.minePeriod ||
      a.otherPeriod - b.otherPeriod ||
      String(a.lastName).localeCompare(String(b.lastName)) ||
      String(a.firstName).localeCompare(String(b.firstName))
    );
  });

  var me = teacherNames(rows, new Set([currentEmail]));
  var them = teacherNames(rows, otherEmails);

  return {
    resolved: true,
    meLast: me.last,
    meFull: me.full,
    otherLast: them.last || String(param),
    otherFull: them.full || String(param),
    students: students,
  };
}

// Resolve a "shared-with" value to a set of teacher emails, matching by full
// email, bare username, email local-part, teacher last name, or full
// teacherName — whatever the caller typed.
function resolveTeachers(rows, param) {
  var raw = normalizeEmail(param);
  var qualified = qualifyEmail(param);
  var out = new Set();
  rows.forEach(function (s) {
    var email = normalizeEmail(s.teacherEmail);
    if (!email) return;
    var local = email.replace(/@.*$/, '');
    var last = String(s.teacherName || '').replace(/,.*$/, '').trim().toLowerCase();
    var full = String(s.teacherName || '').trim().toLowerCase();
    if (email === qualified || email === raw || local === raw || last === raw || full === raw) {
      out.add(email);
    }
  });
  return out;
}

// Distinct last name(s) and full name(s) for a set of teacher emails.
// teacherName is stored "Last, First"; fullName renders it as "First Last".
function teacherNames(rows, emails) {
  var lasts = [];
  var fulls = [];
  rows.forEach(function (s) {
    if (!emails.has(normalizeEmail(s.teacherEmail))) return;
    var raw = String(s.teacherName || '').trim();
    var last = raw.replace(/,.*$/, '').trim();
    var full = fullName(raw);
    if (last && lasts.indexOf(last) === -1) lasts.push(last);
    if (full && fulls.indexOf(full) === -1) fulls.push(full);
  });
  return { last: lasts.join(' / '), full: fulls.join(' / ') };
}

function fullName(raw) {
  var parts = String(raw).split(',');
  if (parts.length === 2) return parts[1].trim() + ' ' + parts[0].trim();
  return String(raw).trim();
}

// Distinct class names from a list of class objects, sorted.
function classNames(list) {
  var names = [];
  list.forEach(function (c) {
    if (names.indexOf(c.name) === -1) names.push(c.name);
  });
  names.sort(function (a, b) { return a.localeCompare(b); });
  return names;
}

function periodNum(p) {
  var n = parseInt(p, 10);
  return isNaN(n) ? 9999 : n;
}

function minPeriod(list) {
  return list.reduce(function (m, c) {
    return Math.min(m, periodNum(c.period));
  }, Infinity);
}

/**
 * Build the shared-overview model for a viewer: every other teacher who shares
 * at least one student with them, each with the list of shared students. The
 * `key` (email username) links to that teacher's ?shared-with= page. Teachers
 * are sorted by last name; students within each by last then first name.
 */
function buildSharedOverview(currentEmail) {
  var rows = readStudents();
  var photos = readPhotoMap();

  var teachersOf = {}; // studentNumber -> Set(teacherEmail)
  var coursesOf = {}; // "studentNumber|teacherEmail" -> Set(course)
  var info = {}; // studentNumber -> identity fields

  rows.forEach(function (s) {
    var email = normalizeEmail(s.teacherEmail);
    if (!email) return;
    var num = String(s.studentNumber);

    (teachersOf[num] = teachersOf[num] || new Set()).add(email);

    var course = String(s.course || '').trim();
    if (course) {
      var k = num + '|' + email;
      (coursesOf[k] = coursesOf[k] || new Set()).add(course);
    }

    if (!info[num]) {
      info[num] = {
        studentNumber: num,
        firstName: s.firstName,
        lastName: s.lastName,
        nickname: s.nickname,
        grade: s.grade,
        gender: s.gender,
        fileId: photos[num] || '',
      };
    }
  });

  // For each of the viewer's students, add them under every other teacher who
  // also teaches them.
  var byTeacher = {}; // otherEmail -> [studentNumber]
  Object.keys(teachersOf).forEach(function (num) {
    var set = teachersOf[num];
    if (!set.has(currentEmail)) return;
    set.forEach(function (email) {
      if (email === currentEmail) return;
      (byTeacher[email] = byTeacher[email] || []).push(num);
    });
  });

  var teachers = Object.keys(byTeacher).map(function (email) {
    var names = teacherNames(rows, new Set([email]));
    var nums = byTeacher[email];

    var students = nums
      .map(function (num) {
        return info[num];
      })
      .sort(function (a, b) {
        return (
          String(a.lastName).localeCompare(String(b.lastName)) ||
          String(a.firstName).localeCompare(String(b.firstName))
        );
      });

    // Distinct course names the shared students take with this teacher, no
    // period — "Spanish II" once, however many periods it runs.
    var courseSet = {};
    nums.forEach(function (num) {
      var set = coursesOf[num + '|' + email];
      if (set) {
        set.forEach(function (c) {
          courseSet[c] = true;
        });
      }
    });
    var courses = Object.keys(courseSet).sort(function (a, b) {
      return a.localeCompare(b);
    });

    return {
      key: email.replace(/@.*$/, ''), // username → ?shared-with=<key>
      last: names.last,
      full: names.full,
      courses: courses,
      students: students,
    };
  });

  teachers.sort(function (a, b) {
    return (
      String(a.last).localeCompare(String(b.last)) ||
      String(a.full).localeCompare(String(b.full))
    );
  });

  return { teachers: teachers };
}

/**
 * (Re)build the `photos` tab by scanning CONFIG.DRIVE_FOLDER_ID for
 * <studentNumber>.jpg files. Run manually from the Apps Script editor after
 * uploading new photos.
 */
function refreshPhotoMap() {
  var folder = DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID);
  var files = folder.getFiles();
  var rows = [];
  while (files.hasNext()) {
    var f = files.next();
    var m = f.getName().match(/^(\d+)\.jpe?g$/i);
    if (m) rows.push([m[1], f.getId()]);
  }
  rows.sort(function (a, b) {
    return Number(a[0]) - Number(b[0]);
  });

  var ss = spreadsheet();
  var sheet = ss.getSheetByName(PHOTOS_SHEET) || ss.insertSheet(PHOTOS_SHEET, ss.getNumSheets());
  sheet.clearContents();
  sheet.getRange(1, 1, 1, 2).setValues([['studentNumber', 'fileId']]);
  if (rows.length) sheet.getRange(2, 1, rows.length, 2).setValues(rows);
  Logger.log('Wrote ' + rows.length + ' photo rows to the "' + PHOTOS_SHEET + '" tab.');
}

/* ------------------------------------------------------------------ */
/* Spreadsheet helpers                                                 */
/* ------------------------------------------------------------------ */

function spreadsheet() {
  return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);
}

/** Student rows come from the first tab of the spreadsheet. */
function readStudents() {
  return sheetToObjects(spreadsheet().getSheets()[0]);
}

/** studentNumber -> fileId from the `photos` tab. */
function readPhotoMap() {
  var sheet = spreadsheet().getSheetByName(PHOTOS_SHEET);
  var map = {};
  if (!sheet) return map;
  sheetToObjects(sheet).forEach(function (r) {
    if (r.studentNumber !== '' && r.studentNumber != null) {
      map[String(r.studentNumber)] = String(r.fileId);
    }
  });
  return map;
}

/**
 * Lowercased Set of admin emails from the `admins` tab. Reads every cell and
 * keeps anything that resolves to an email — bare usernames get @berkeley.net
 * appended — so the tab can be a plain list of names or full addresses, with or
 * without a header row. (A stray label like "email" becomes
 * "email@berkeley.net", which matches nobody's login and is harmless.)
 */
function readAdmins() {
  var sheet = spreadsheet().getSheetByName(ADMINS_SHEET);
  var out = new Set();
  if (!sheet) return out;
  sheet.getDataRange().getValues().forEach(function (row) {
    row.forEach(function (cell) {
      var email = qualifyEmail(cell);
      if (isEmailShaped(email)) out.add(email);
    });
  });
  return out;
}

/** Read a sheet into an array of objects keyed by the header row. */
function sheetToObjects(sheet) {
  var values = sheet.getDataRange().getValues();
  if (values.length < 2) return [];
  var headers = values[0].map(function (h) {
    return String(h).trim();
  });
  return values
    .slice(1)
    .filter(function (row) {
      return row.some(function (c) {
        return c !== '' && c !== null;
      });
    })
    .map(function (row) {
      var o = {};
      headers.forEach(function (h, i) {
        o[h] = row[i];
      });
      return o;
    });
}

/* ------------------------------------------------------------------ */
/* Small utilities                                                     */
/* ------------------------------------------------------------------ */

function slugify(s) {
  return String(s)
    .replace(/\s+/g, '-')
    .replace(/[^-\w]/g, '')
    .toLowerCase();
}

function normalizeEmail(s) {
  return String(s || '').trim().toLowerCase();
}

// Normalize an email or bare username: trim + lowercase, and append
// @berkeley.net when no domain is given, so "peterseibel" becomes
// "peterseibel@berkeley.net". Used for both the admins tab and ?as=.
function qualifyEmail(s) {
  var v = normalizeEmail(s);
  if (!v) return '';
  if (v.indexOf('@') === -1) v = v + '@berkeley.net';
  return v;
}

function isEmailShaped(s) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
}

function isBerkeleyStaff(email) {
  return /@berkeley\.net$/.test(email);
}

function jsonForScript(obj) {
  // Safe to inline inside a <script> via <?!= ?>: escape "<" so a value can
  // never terminate the script element.
  return JSON.stringify(obj).replace(/</g, '\\u003c');
}

function page(template) {
  return template
    .evaluate()
    .setTitle('Facecards')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function getBaseUrl() {
  try {
    return ScriptApp.getService().getUrl() || '';
  } catch (err) {
    return '';
  }
}
