#!/usr/bin/env bash

set -euo pipefail

source .cookie

PHOTO_DIR=photos-2024-25

personId="$1"
studentNumber="$2"

# Got the curl command below by loading a page with an image on it and then
# right clicking on the URL in the Network tab of the Chrome dev tools and
# choosing "Copy as cURL". Will need to refresh the cookie value in .cookie from
# time to time by doing the same and then grabbing the -b value.

curl "https://berkeleyca.infinitecampus.org/campus/personPicture.jsp?personID=$personId&alt=default-person-picture" \
  -H 'accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'accept-language: en-US,en;q=0.9' \
  -b "$COOKIE" \
  -H 'priority: i' \
  -H "referer: https://berkeleyca.infinitecampus.org/campus/sis/tools-student/summary/beta?year=2026&schoolID=5&calendarID=702&structureID=711&selectedPersonID=$personId&appName=berkeley" \
  -H 'sec-ch-ua: "Not)A;Brand";v="8", "Chromium";v="138", "Google Chrome";v="138"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: image' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36' \
  -o "$PHOTO_DIR/$studentNumber.jpg"
